### ISSUE TITLE
PWA book repo link missing

### ISSUE THREAD

**Issue by yipcma** [TalAter/awesome-progressive-web-apps#8]
Hi TalAter,

I'm reading your pre-release book on PWA, but I couldn't find the link to the code that is used from chapter 2. Could you please put a link? Thank you very much.

Andrew

**Comment by TalAter** [comment]
I have just published it: https://github.com/TalAter/gotham_imperial_hotel

Being early release, the code changes almost daily. It's also a "completed" project with most of the DIY exercises from the book already implemented... Closer to the release of the book, I will have a final version, that lets you check out a snapshot of the project at each stage (i.e. what it looks like at the beginning and end of each chapter).

I would **love** ❤️ to get your feedback on it. What was clear, what wasn't, what needs improving, what you liked, etc. Feel free to be as brutal as you'd like in your feedback 😃
